### PR TITLE
Update/Change

### PR DESCRIPTION
**Pull request by dwhitnall**
Added email function to let know when successfully download sub, and when removing from database when given number of days can't find any

### CODE REVIEW

**Comment by Sakartu** [comment]
Before I can merge this, could you fix some [PEP8](http://legacy.python.org/dev/peps/pep-0008/) violations?
- Use 4 spaces instead of tabs 
- Don't use capital letters for variables

Also, python sqlite3 supports storing datetime.date and datetime.datetime [natively](https://docs.python.org/2/library/sqlite3.html#default-adapters-and-converters). Could you rewrite the date parsing using this support?

If you don't have the time, and enough people want this functionality, I could port it myself, but since I don't really need it it's not at the top of my priority list...

**Comment by Sakartu** [comment]
Since I liked your suggestion for a "countdown" for each ep after which it's cleaned from the database, I have implemented such a feature in commit b31f390. If you want your email feature as well, please implement it based on the latest commit.

**Comment by dwhitnall** [comment]
Sure thanks this is the first time I have used both python and git, still learning. I see what you mean about the date function much neater.

**Comment by dwhitnall** [comment]
so i couldn't seem to figure out how to update my fork from your commit, so i ended up removing my fork and starting agin

**Comment by Sakartu** [comment]
Closed in favor of the single e-mail addition pull request

**Pull request closed without merging**
